### ISSUE TITLE
Converting code to swift

### ISSUE THREAD

**Issue by pan-long** [ajkoshy7/SubTable#1]
Hello @ajkoshy7, I found this project is useful and helped me in my project. As I start iOS programming with swift, are your considering translating the code into swift? I mean myself know how to use objective-c library with swift, but it might be helpful for some beginners like me. Cheers!

**Comment by ajkoshy7** [comment]
Hi @pan-long, I'm glad this project was able to help you out! That's a great point that I haven't yet considered. It's been on my mind to come back to this project and improve on it. When I do, I'll be sure to integrate a swift version. If you end up with some helpful modifications of your own, keep me posted!
